### ISSUE TITLE
[Bug] Crash/Freeze when Playing Video Background due to Resolution of video (?)

### ISSUE THREAD

**Issue by YuevUwU** [TeamFlos/phira#279]
---

发生版本：v0.6.2 (已测试Android与iOS)
中文标题：播放视频背景时闪退/卡死

---

谱面：[[13080] ♿Nuclear-Star♿](https://phira.moe/chart/13080)
分区：未上架 - 整活
演示：[视频](https://github.com/TeamFlos/phira/assets/96368079/2e245abc-3149-4a86-b799-fe542c0249a3)
具体情况：
1. HONOR PAD V7 PRO (Android 11)
清黄键海(2228combo)时造成闪退 (即视频背景播放时)
2. POCO M5/M5s (Android 13) (v8a)
黄键海期间(约3171，浮动)，帧率由120降至60，直接卡死 (即视频背景播放时)
---

谱面：[[2789] 耳光侠](https://phira.moe/chart/2789)
分区：未上架 - 整活
演示：[视频](https://github.com/TeamFlos/phira/assets/96368079/712a48d3-8616-4eaf-b9e0-641e84c2273e)
具体情况：
1. HONOR PAD V7 PRO (Android 11)
进入谱面闪退
2. POCO M5/M5s (Android 11) (v8a)
进入谱面卡死，未播放视频背景
---

谱面：[[13967] enchanted love](https://phira.moe/chart/13967)
分区：未上架 - 常规
1. iPad(?) (iOS 17.4.1)
进入谱面闪退
2. POCO M5/M5s (Android 11) (v8a)
进入谱面卡死
---

设备提供者：
HONOR PAD V7 PRO：Mosacaio
POCO M5/M5s：YuevUwU
iPad(?)：sword

**Comment by YuevUwU** [comment]
LINUX BINARY LOG OUTPUT:
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `408960`,
 right: `414720`', /home/mivik/.cargo/git/checkouts/prpr-miniquad-4ecc38303101db59/e8deff6/src/graphics/texture.rs:302:9
stack backtrace:
   0:     0x56165f5a90aa - <unknown>
   1:     0x56165f5d4d1e - <unknown>
   2:     0x56165f5a2535 - <unknown>
   3:     0x56165f5a8e75 - <unknown>
   4:     0x56165f5aa7ff - <unknown>
   5:     0x56165f5aa53b - <unknown>
   6:     0x56165f5aaf69 - <unknown>
   7:     0x56165f5aad09 - <unknown>
   8:     0x56165f5a955c - <unknown>
   9:     0x56165f5aaa12 - <unknown>
  10:     0x56165f5d1f13 - <unknown>
  11:     0x56165f5d22cf - <unknown>
  12:     0x56165f57429b - <unknown>
  13:     0x56165f57e253 - <unknown>
  14:     0x56165ecebb57 - <unknown>
  15:     0x56165ece94b4 - <unknown>
  16:     0x56165eccc36c - <unknown>
  17:     0x56165ecab368 - <unknown>
  18:     0x56165e584112 - <unknown>
  19:     0x56165e586777 - <unknown>
  20:     0x56165f3d155d - <unknown>
  21:     0x56165e565a66 - <unknown>
  22:     0x56165e5660a0 - <unknown>
  23:     0x56165e50fc5e - <unknown>
  24:     0x56165e5db715 - <unknown>
  25:     0x56165e45d0f3 - <unknown>
  26:     0x56165e45d109 - <unknown>
  27:     0x56165f59a32c - <unknown>
  28:     0x56165e45d165 - <unknown>
  29:     0x7f37e5515d90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  30:     0x7f37e5515e40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  31:     0x56165e45d025 - <unknown>
  32:                0x0 - <unknown>
Segmentation fault (core dumped)
```

**Comment by YuevUwU** [comment]
后续补充，以2789为例，length of buf[0] 变成414720，预期为852*480=408960 (format=Alpha, size加成系数=1)
现buf中YUV值长度如下: (yuv420p)
buf[0] (Y): 414720 (预期408960) (data)
buf[1] (U): 107520 (预期204480) (data_half)
buf[2] (V): 107520 (预期204480) (data_half)
几个数字有些特性(可能误导)
864*480=414720 (18:10)
448*240=107520 (28:15)
0.6.4版去掉miniquad所有assert後，画面变得异常地...啥(如图)
希望对日后想修复这个Bug的开发者有些帮助
(另外这可能不是 OS/Device Compatibility Bug)

![Screenshot_2024-10-21-03-19-15-387_com.anydesk.anydeskandroid-edit.jpg](https://github.com/user-attachments/assets/fb6338f2-97c2-4cdb-97e6-be7c2037bef0)

**Comment by FOTL09** [comment]
Hello Dev of Phira, if you see this comment then im messaging to you, because of a thing happen
it started on newest ver of Phira, after i downloaded to my device and it happened, here is the link to file 
https://drive.google.com/file/d/1NdasAxWCQJ5YweBqqC4ro0Jfg5Ps3Z20/view

**Comment by YuevUwU** [comment]
Tested on Linux self-built based on v0.6.4
```
thread 'main' panicked at /home/alan54692/.cargo/git/checkouts/prpr-miniquad-4ecc38303101db59/e8deff6/src/graphics/texture.rs:302:9:
assertion `left == right` failed
  left: 388800
 right: 397440
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at core/src/panicking.rs:221:5:
panic in a function that cannot unwind
... (The same log after it)
```

**Comment by YuevUwU** [comment]
## NEW CLUE
The result seems to be related to resolution

### Reproduction
Test Version: Release v0.6.7 Windows (Official)
Device: MSI Cyborg 14 A13V
GPU: NVIDIA RTX 4060
CUDA: V12.6.85
FFmpeg: ffmpeg version N-118328-g504df09c34-20250121


1. Prepare videos with different resolution, such as
  ```
  ffmpeg -f lavfi -i testsrc=size=1280x720:rate=30 -t 10 -c:v libx264 -pix_fmt yuv420p bga.mp4
  ```
2. Get any chart (aspect-ratio=16:9) and inject `extra.json` like this
  ```json
  {
      "bpm": [
         { "time": [0, 0, 1], "bpm" : 160.0 }
      ],
     "videos": [{
         "path": "bga.mp4",
         "time": [2, 0, 1],
         "scale": "cropCenter",
         "alpha": 1.0,
         "dim": 0.6
     }]
  }
  ```
2. Observe what will terminal print (in stupid way..)
  (The rows which have no value in middle is working without error)

| Resolution | Got (Left) | Left multipl. | Right multipl. | Expected (Right) | Orig. Ratio |
|---:|:---:|:---:|:---:|:---:|---:|
| 1920x1080 |  |  |  |  | 16:9,1.777 |
| 1280x720 |  |  |  |  | 16:9,1.777 |
| 640x360 |  |  |  |  | 16:9,1.777 |
| 640x480 |  |  |  |  | 4:3,1.333 |
| 768x480 |  |  |  |  | 16:10,1.600 |
| 1152x720 |  |  |  |  | 16:10,1.600 |
| 800x480 | 400x240 | 96000 | 99840 | 416x240 | 26:15,1.733 |
| 832x480 |  |  |  |  | 26:15,1.733 |
| 840x480 | 840x480 | 403200 | 414720 | 864x480 | 7:4,1.75 |
| 848x480 | 848x480 | 407040 | 414720 | 864x480 | 53:30,1.766 |
| 850x480 | 850x480 | 408000 | 414720 | 864x480 |  |
| 852x480 | 852x480 | 408960 | 414720 | 864x480 | 71:40,1.775 |
| 854x480 | 854x480 | 409920 | 414720 | 864x480 | 427:240,1.779 |
| 864x480 | 432×240 | 103680 | 107520 | 448x240 | 18:10,1.800 |
| 426x240 | 426x240 | 102240 | 107520 | 448x240 | 18:10,1.800 |
| 1728x960 |  |  |  |  | 18:10,1.800 |
| 896x480 |  |  |  |  | 28:15,1.866 |
| 896x482 |  |  |  |  |  |
| 896x484 |  |  |  |  |  |
| 896x486 |  |  |  |  |  |
| 1282x722 | 1282x722 | 925604 | 947264 | 1312x722 |  |
| 1284x724 | 1284x724 | 929616 | 949888 | 1312x724 |  |
| 768x766 |  |  |  |  |  |
| 766x768 | 766x768 | 588288 | 589824 | 768x768 | 1:1,1.000 |
| 720x1280 | 720x1280 | 921600 | 942080 | 736x1280 | 9:16,0.562 |
| 512x512 |  |  |  |  | 1:1,1.000 |
| 720x720 | 720x720 | 518400 | 529920 | 736x720 | 1:1,1.000 |
| 1080x1080 | 1080x1080 | 1166400 | 1175040 | 1088x1080 | 1:1,1.000 |
| 1088x1080 |  |  |  |  |  |

***[WARNING: PROBABLY MISLEADING INFERENCE BELOW]***
It seems like I need to ensure `max(w,h)` of resolution is a multiple of 64?
idk...and I didn't change other factor (such as h264, yuv420p, RGBA)
A certain AI said that it's about row-pitch alignment and block alignment of GPU..? Evidence needed
(so it may really a compatibility issue?)
And why it only happens on v0.6.2+ ? is it really related to unlock video feature changes?

### Chart mentioned above
```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '.\2789\Slap.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf61.9.106
    description     : Packed by Bilibili XCoder v2.0.2
  Duration: 00:01:11.98, start: 0.000000, bitrate: 1226 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 864x480, 1091 kb/s, 30 fps, 30 tbr, 15360 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
      encoder         : Lavc61.31.101 libx264
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 127 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
```
```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '.\13967\ETL.MP4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf59.27.100
  Duration: 00:02:10.03, start: 0.000000, bitrate: 578 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1438x918 [SAR 1:1 DAR 719:459], 437 kb/s, 50 fps, 50 tbr, 12800 tbn (default)
    Metadata:
      handler_name    : Core Media Video
      vendor_id       : [0][0][0][0]
      encoder         : Lavc59.37.100 libx264
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 130 kb/s (default)
    Metadata:
      handler_name    : Core Media Audio
      vendor_id       : [0][0][0][0]
```
```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '.\YS.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    date            : UTC 2023-10-15 04:39:54
    encoder         : Lavf59.27.100
  Duration: 00:02:42.37, start: 0.000000, bitrate: 767 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1440x1080 [SAR 1:1 DAR 4:3], 632 kb/s, 60 fps, 60 tbr, 15360 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
      encoder         : Lavc59.37.100 libx264
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 122 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
```
### Temporary Solution(?)
I use last one ( @ghost ) for example: `1440 / 64 = 22.5`. To avoid loss info, I choose to double the resolution to `2880x`. Of course you can choose any multiple of 64 as width. (`-1` below means auto-calculate the height without ratio loss)
```
ffmpeg.exe -i .\YS-orig.mp4 -vf scale="2880:-1" .\YS.mp4
```
So let's re-archive them...hmm...it exactly work..!

### Footer
Thanks for @Vanilla6770 providing his successful chart with video background (1280x720)
And I'm apologize that Video Background is totally broken! I'm too pessimistic...

**Comment by YuevUwU** [comment]
Fixed on https://github.com/TeamFlos/phira/commit/2cf1f6af4ee0e8393b9809128f4469d77715f448

Tested 2789 and 13967
13080 has been removed

THANKS MIVIK!!!!!!!!!!!!!!!!!!!!!!!
