### ISSUE TITLE
[bug] Can't display `del-confirm` normally (fr-FR, pt-BR) (v0.5.0+)

### ISSUE THREAD

**Issue by YuevUwU** [TeamFlos/phira#313]
### Basic Info:
**Reporter:** Mr_LemAud
**Version:** v0.5.0 - v0.6.2
**Expected:** Like page label, display as glyph in bold.ttf or phigros.ttf
### Français
  Expected: Êtes-vous sûr de vouloir supprimer ?
  Screenshot:
![image](https://github.com/TeamFlos/phira/assets/96368079/ff687eb0-70f0-4648-b78c-69f921af11d9)
### Português
  Expected: Você tem certeza que quer deletar?
  Screenshot:
![image](https://github.com/TeamFlos/phira/assets/96368079/8e60717d-8eb1-409b-81da-2ad51407729e)
### Some Possible Fixes by Mr_LemAud
1) remove all accents, they aren't that much important to French speakers either way, but it'll be just putting the problem under the rug
2) Fix this proper, but that'll take time
3) Ignore it cause I can definitely still understand what it says (I do not recommend)

**Comment by YuevUwU** [comment]
At 2024/5/25 early morning (UTC+8), developer sjfhsjfh temporarily solved this problem by updating the font. 
However, this problem may still recur in the future, such as Vietnamese characters that have not been updated with this font, and other non-languages ​​in the future. 
Therefore, unless the developer closes this issue himself, I will keep it open before the code-based fix.

**Comment by YuevUwU** [comment]
Tested on v0.6.7 (Android/Windows) on 2025/11/14
The issue can be reproduced again under fr-FR
(Confirmed that `bold font not modified` and those character not shown in bold.ttf with fontforge)

sha256: 470f7bba81da3f110b4444756ae6cc94e7dfdaeed5adab4889f99af659172d4c assets/bold.ttf

**Comment by YuevUwU** [comment]
## vi-VN `del-confirm` panic issue (Unreleased)
**Test Commit:** 
- `tags/v0.6.7` (with `ahash` 0.8.7 for latest nightly)
- latest commit `986be9c Merge pull request #491 from YuevUwU/en-US`

**Description:** Vietnamese `del-confirm` will panic (exceed the boundary in #399 )
**Environment:**
```
vboxuser@vbox:~/Desktop/phira$ cargo +stable --version
cargo 1.91.1 (ea2d97820 2025-10-10)
vboxuser@vbox:~/Desktop/phira$ cargo +nightly --version
cargo 1.93.0-nightly (636800288 2025-10-31)
vboxuser@vbox:~/Desktop/phira$ cargo +nightly-2023-02-01 --version
cargo 1.69.0-nightly (3c5af6bed 2023-01-24)
vboxuser@vbox:~/Desktop/phira$ RUST_BACKTRACE=full cargo +stable run --target x86_64-unknown-linux-gnu --bin phira-main
```
Diff Patch for v0.6.7
```diff
diff --git a/phira/locales/vi-VN/common.ftl b/phira/locales/vi-VN/common.ftl
index 9caec67..ac3aaac 100644
--- a/phira/locales/vi-VN/common.ftl
+++ b/phira/locales/vi-VN/common.ftl
@@ -1,5 +1,5 @@

del-confirm = Bạn có chắc chắn muốn [-xóa?-]{+xoá không ?+}
del-confirm-content = Hành động này không thể hoàn tác.

cancel = Hủy
```
### Backtrace (stable, 986be9c, debug, RUST_BACKTRACE=1, log of this thread only)
```rs
thread 'main' (196246) panicked at prpr/src/ui/text.rs:180:36:
byte index 2 is not a char boundary; it is inside 'ạ' (bytes 1..4) of `Bạn có chắc chắn muốn xoá không ?`
stack backtrace:
   0: __rustc::rust_begin_unwind
             at /rustc/ed61e7d7e242494fb7057f2657300d9e77bb4fcb/library/std/src/panicking.rs:698:5
   1: core::panicking::panic_fmt
             at /rustc/ed61e7d7e242494fb7057f2657300d9e77bb4fcb/library/core/src/panicking.rs:75:14
   2: core::str::slice_error_fail_rt
   3: core::str::slice_error_fail
             at /rustc/ed61e7d7e242494fb7057f2657300d9e77bb4fcb/library/core/src/str/mod.rs:69:5
   4: core::str::traits::<impl core::slice::index::SliceIndex<str> for core::ops::range::RangeTo<usize>>::index
             at /rustc/ed61e7d7e242494fb7057f2657300d9e77bb4fcb/library/core/src/str/traits.rs:479:21
   5: core::str::traits::<impl core::ops::index::Index<I> for str>::index
             at /rustc/ed61e7d7e242494fb7057f2657300d9e77bb4fcb/library/core/src/str/traits.rs:63:15
   6: prpr::ui::text::DrawText::measure_inner
             at ./prpr/src/ui/text.rs:180:36
   7: prpr::ui::text::DrawText::draw_with_font
             at ./prpr/src/ui/text.rs:213:37
   8: prpr::ui::text::DrawText::draw_using::{{closure}}
             at ./prpr/src/ui/text.rs:243:29
   9: std::thread::local::LocalKey<T>::try_with
             at /rustc/ed61e7d7e242494fb7057f2657300d9e77bb4fcb/library/std/src/thread/local.rs:315:12
  10: std::thread::local::LocalKey<T>::with
             at /rustc/ed61e7d7e242494fb7057f2657300d9e77bb4fcb/library/std/src/thread/local.rs:279:20
  11: prpr::ui::text::DrawText::draw_using
             at ./prpr/src/ui/text.rs:243:14
  12: prpr::ui::dialog::Dialog::render::{{closure}}
             at ./prpr/src/ui/dialog.rs:209:18
  13: prpr::ui::Ui::scope
             at ./prpr/src/ui.rs:741:19
  14: prpr::ui::dialog::Dialog::render
             at ./prpr/src/ui/dialog.rs:190:12
  15: prpr::scene::Main::render::{{closure}}
             at ./prpr/src/scene.rs:530:28
  16: std::thread::local::LocalKey<T>::try_with
             at /rustc/ed61e7d7e242494fb7057f2657300d9e77bb4fcb/library/std/src/thread/local.rs:315:12
  17: std::thread::local::LocalKey<T>::with
             at /rustc/ed61e7d7e242494fb7057f2657300d9e77bb4fcb/library/std/src/thread/local.rs:279:20
  18: prpr::scene::Main::render
             at ./prpr/src/scene.rs:528:20
  19: phira::the_main::{{closure}}::{{closure}}
             at ./phira/src/lib.rs:221:18
  20: phira::the_main::{{closure}}
             at ./phira/src/lib.rs:219:19
  21: phira::quad_main::{{closure}}
             at ./phira/src/lib.rs:305:38
  22: macroquad::exec::resume
             at /home/vboxuser/.cargo/git/checkouts/prpr-macroquad-23a56986f96b3274/dae5b57/src/exec.rs:72:27
  23: <macroquad::Stage as miniquad::event::EventHandler>::draw::{{closure}}
             at /home/vboxuser/.cargo/git/checkouts/prpr-macroquad-23a56986f96b3274/dae5b57/src/lib.rs:667:24
  24: <macroquad::Stage as miniquad::event::EventHandler>::draw::maybe_unwind
             at /home/vboxuser/.cargo/git/checkouts/prpr-macroquad-23a56986f96b3274/dae5b57/src/lib.rs:658:21
  25: <macroquad::Stage as miniquad::event::EventHandler>::draw
             at /home/vboxuser/.cargo/git/checkouts/prpr-macroquad-23a56986f96b3274/dae5b57/src/lib.rs:663:26
  26: miniquad::native::linux_x11::glx_main_loop
             at /home/vboxuser/.cargo/git/checkouts/prpr-miniquad-43823a28bf246e16/bb60ff8/src/native/linux_x11.rs:742:14
  27: miniquad::native::linux_x11::run
             at /home/vboxuser/.cargo/git/checkouts/prpr-miniquad-43823a28bf246e16/bb60ff8/src/native/linux_x11.rs:904:39
  28: miniquad::start
             at /home/vboxuser/.cargo/git/checkouts/prpr-miniquad-43823a28bf246e16/bb60ff8/src/lib.rs:190:17
  29: macroquad::Window::from_config
             at /home/vboxuser/.cargo/git/checkouts/prpr-macroquad-23a56986f96b3274/dae5b57/src/lib.rs:744:9
  30: quad_main
             at ./phira/src/lib.rs:304:5
  31: phira_main::main
             at ./phira-main/src/main.rs:2:5
  32: core::ops::function::FnOnce::call_once
             at /rustc/ed61e7d7e242494fb7057f2657300d9e77bb4fcb/library/core/src/ops/function.rs:250:5
```

**Comment by sjfhsjfh** [comment]
The font is distributed dynamically now iirc. Maybe @Mivik should update the font file on the CDN?

**Comment by YuevUwU** [comment]
> This may be fixed after this PR is merged, since only then the character set could be determined.

As sjfh said, the character set could be determined. Maybe confirm it on v0.6.7 to avoid some characters not be used in the latest tree (rarely). Of course, the union of them is definitely the best solution.

> The issue can be reproduced again under fr-FR (in latest release v0.6.7)

**Comment by YuevUwU** [comment]
I'm guessing the intention of [efe54b8](https://github.com/TeamFlos/phira/commit/efe54b81546149ca8d083f3528e326f2b09b2326)
### Test on
[efe54b8](https://github.com/TeamFlos/phira/commit/efe54b81546149ca8d083f3528e326f2b09b2326)
- with https://github.com/TeamFlos/phira/pull/614#issuecomment-3531792741 (else I can't enter chart info)
- with the patch below
  ```
  diff --git a/phira/locales/fr-FR/common.ftl b/phira/locales/fr-FR/common.ftl
  index 0a90859..453ac83 100644
  --- a/phira/locales/fr-FR/common.ftl
  +++ b/phira/locales/fr-FR/common.ftl
  @@ -1,5 +1,5 @@
   
  -del-confirm = Supprimer
  +del-confirm = Êtes-vous sûr de vouloir supprimer ?
   del-confirm-content = Cette action est irréversible. Appuyez sur « Confirmer » pour continuer.
   
   cancel = Annuler
  ```
### Result
- vi-VN: PANIC
- Patched fr-FR
  <img width="976" height="611" alt="Image" src="https://github.com/user-attachments/assets/d0d7ca7e-caa1-4d77-ada3-fd0aad135eb1" />
- pt-BR
  <img width="981" height="639" alt="Image" src="https://github.com/user-attachments/assets/75c8eb3d-4520-4c83-934c-f5ecf30e7aea" />
### Environment
- **OS:** Linux Mint 22.1 x86_64
- **Host:** VirtualBox (1.2) (not clean, VMSVGA, 3D Accel disabled)
- **Shell:** bash 5.2.21
- **Display (Virtual1):** 1816x1078, 60 Hz
- **DE:** Xfce4 4.18
- **WM:** Xfwm4 (X11)
- **libc6:** 2.39-0ubuntu8.6
- **cargo:** 1.91.1 (ea2d97820 2025-10-10)
- **CPU:** 13th Gen Intel(R) Core(TM) i7-13620H (8) @ 2.92 GHz
- **GPU:** VMware SVGA II Adapter (NVIDIA GeForce RTX 4060 Laptop)

SHA256
470f7bba81da3f110b4444756ae6cc94e7dfdaeed5adab4889f99af659172d4c  assets/bold.ttf
64faa1f96a8293f64afde3e1d1ab7724485998836a7b8218865951eb193f7975  assets/font.ttf
15d2d38a1041a99148ae9940c88833caea28291b311cbc61126325c9cca02dd2  assets/phigros.ttf
44cdad5a661605228f538c348baba7e4607026b9cc77c6fc10e7d676d8f6e619  data/bold.ttf

***(Tell me if it work expectedly for anyone, thank you)***
***(Also, Thanks for Mivik's notice)***

**Comment by YuevUwU** [comment]
This issue is solved with #629 (2d87f1700b7bfcde5263a638fa892d1f2d121786) , thanks to all contributors 🙏 

Test on Windows 11 26200.7462 (cross-built from WSL2 Ubuntu 24.04)

- vi-VN

<img width="975" height="640" alt="Image" src="https://github.com/user-attachments/assets/c9e3011a-a3f8-4429-9ab2-3f803a551a52" />

- pt-BR

<img width="1369" height="826" alt="Image" src="https://github.com/user-attachments/assets/d71aa428-1741-437a-b29d-f47b00de814a" />

- fr-FR translation has been modified at [`2f4fe23`](https://github.com/TeamFlos/phira/commit/2f4fe234b55607f030a6dc55b4db6681ffb85b8e#diff-64987e6ad31335cac4550ca83f8609ccf8cdca3cfd03997de147ea4e0a4dd1e1L2), it has been shorter
